"""'增加私聊好友表'

Revision ID: 442a866dc869
Revises: 77dd9fd93eef
Create Date: 2019-08-08 17:13:57.207098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '442a866dc869'
down_revision = '77dd9fd93eef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends_strategy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=126), nullable=True, comment='添加好友策略'),
    sa.Column('create_time', sa.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DATETIME(), nullable=True, comment='修改时间'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='状态'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_friend_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户'),
    sa.Column('name', sa.String(length=126), nullable=True, comment='好友分组组名'),
    sa.Column('create_time', sa.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DATETIME(), nullable=True, comment='修改时间'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='状态'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_friend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('self', sa.Integer(), nullable=True, comment='自己'),
    sa.Column('friend', sa.Integer(), nullable=True, comment='好友'),
    sa.Column('is_pass', sa.Boolean(), nullable=True, comment='审核通过'),
    sa.Column('remark', sa.String(length=126), nullable=True, comment='名称备注'),
    sa.Column('top', sa.Boolean(), nullable=True, comment='置顶'),
    sa.Column('become_friends_time', sa.DATETIME(), nullable=True, comment='成为好友的时间'),
    sa.Column('group_id', sa.Integer(), nullable=True, comment='分组'),
    sa.Column('room', sa.String(length=126), nullable=True, comment='房间名称'),
    sa.Column('create_time', sa.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DATETIME(), nullable=True, comment='修改时间'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='状态'),
    sa.ForeignKeyConstraint(['group_id'], ['chat_friend_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_friend_friend'), 'chat_friend', ['friend'], unique=False)
    op.create_index(op.f('ix_chat_friend_self'), 'chat_friend', ['self'], unique=False)
    op.add_column('user', sa.Column('friends_strategy_id', sa.Integer(), nullable=True, comment='添加好友策略'))
    op.create_foreign_key(None, 'user', 'friends_strategy', ['friends_strategy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'friends_strategy_id')
    op.drop_index(op.f('ix_chat_friend_self'), table_name='chat_friend')
    op.drop_index(op.f('ix_chat_friend_friend'), table_name='chat_friend')
    op.drop_table('chat_friend')
    op.drop_table('chat_friend_group')
    op.drop_table('friends_strategy')
    # ### end Alembic commands ###
