"""'修改好友表结构'

Revision ID: 758d175af84e
Revises: d5ba0761864c
Create Date: 2019-08-09 10:04:44.843907

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '758d175af84e'
down_revision = 'd5ba0761864c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_friend', sa.Column('friend_id', sa.Integer(), nullable=True, comment='好友'))
    op.add_column('chat_friend', sa.Column('self_id', sa.Integer(), nullable=True, comment='自己'))
    op.drop_index('ix_chat_friend_friend', table_name='chat_friend')
    op.drop_index('ix_chat_friend_self', table_name='chat_friend')
    op.create_foreign_key(None, 'chat_friend', 'user', ['friend_id'], ['id'])
    op.create_foreign_key(None, 'chat_friend', 'user', ['self_id'], ['id'])
    op.drop_column('chat_friend', 'self')
    op.drop_column('chat_friend', 'friend')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_friend', sa.Column('friend', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='好友'))
    op.add_column('chat_friend', sa.Column('self', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='自己'))
    op.drop_constraint(None, 'chat_friend', type_='foreignkey')
    op.drop_constraint(None, 'chat_friend', type_='foreignkey')
    op.create_index('ix_chat_friend_self', 'chat_friend', ['self'], unique=False)
    op.create_index('ix_chat_friend_friend', 'chat_friend', ['friend'], unique=False)
    op.drop_column('chat_friend', 'self_id')
    op.drop_column('chat_friend', 'friend_id')
    # ### end Alembic commands ###
