"""'重新生成'

Revision ID: 77dd9fd93eef
Revises: 
Create Date: 2019-08-03 21:52:04.191841

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa
from sqlalchemy import SmallInteger
from apps.user.model import User


# revision identifiers, used by Alembic.
revision = '77dd9fd93eef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True, comment='反馈类型'),
    sa.Column('create_time', sa.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DATETIME(), nullable=True, comment='修改时间'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='状态'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True, comment='权限名称'),
    sa.Column('create_time', sa.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DATETIME(), nullable=True, comment='修改时间'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='状态'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True, comment='角色名称'),
    sa.Column('create_time', sa.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DATETIME(), nullable=True, comment='修改时间'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='状态'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles_permissions',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], )
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(length=64), nullable=False, comment='用户名'),
    sa.Column('pwd', sa.String(length=256), nullable=False, comment='密码'),
    sa.Column('nickName', sa.String(length=64), nullable=False, comment='昵称'),
    sa.Column('sex', sqlalchemy_utils.types.choice.ChoiceType(User.USER_SEX,SmallInteger()), nullable=True, comment='性别'),
    sa.Column('birth', sa.DATE(), nullable=True, comment='生日'),
    sa.Column('portrait', sa.String(length=256), nullable=False, comment='头像'),
    sa.Column('email', sa.String(length=128), nullable=True, comment='邮箱'),
    sa.Column('is_email', sa.Boolean(), nullable=True, comment='认证邮箱'),
    sa.Column('province', sa.String(length=64), nullable=True, comment='省份'),
    sa.Column('city', sa.String(length=64), nullable=True, comment='城市'),
    sa.Column('home', sa.String(length=64), nullable=True, comment='地区'),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DATETIME(), nullable=True, comment='修改时间'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='状态'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('userName')
    )
    op.create_table('chat_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True, comment='聊天室名称'),
    sa.Column('create_user', sa.Integer(), nullable=True, comment='创建人'),
    sa.Column('img', sa.String(length=256), nullable=True, comment='聊天室封面图'),
    sa.Column('desc', sa.String(length=512), nullable=True, comment='聊天室简介'),
    sa.Column('create_time', sa.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DATETIME(), nullable=True, comment='修改时间'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='状态'),
    sa.ForeignKeyConstraint(['create_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('feedback_reply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False, comment='回复标题'),
    sa.Column('content', sa.TEXT(), nullable=False, comment='回复内容'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='回复人'),
    sa.Column('create_time', sa.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DATETIME(), nullable=True, comment='修改时间'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='状态'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True, comment='信息发表房间'),
    sa.Column('user_id', sa.String(length=256), nullable=True, comment='信息发表人'),
    sa.Column('msg', sa.String(length=256), nullable=True, comment='聊天信息'),
    sa.Column('create_time', sa.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DATETIME(), nullable=True, comment='修改时间'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='状态'),
    sa.ForeignKeyConstraint(['room_id'], ['chat_room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False, comment='反馈内容'),
    sa.Column('contact', sa.String(length=128), nullable=True, comment='反馈联系方式'),
    sa.Column('type_id', sa.Integer(), nullable=True, comment='反馈类型'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='创建人'),
    sa.Column('reply_id', sa.Integer(), nullable=True, comment='官方回复'),
    sa.Column('image', sa.String(length=256), nullable=True, comment='反馈问题截图封面'),
    sa.Column('create_time', sa.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DATETIME(), nullable=True, comment='修改时间'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='状态'),
    sa.ForeignKeyConstraint(['reply_id'], ['feedback_reply.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['feedback_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_chat_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=256), nullable=True),
    sa.Column('chat_room_id', sa.Integer(), nullable=True),
    sa.Column('is_create_user', sa.Boolean(), nullable=True, comment='角色'),
    sa.Column('create_time', sa.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DATETIME(), nullable=True, comment='修改时间'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='状态'),
    sa.ForeignKeyConstraint(['chat_room_id'], ['chat_room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_chat_room_chat_room_id'), 'user_chat_room', ['chat_room_id'], unique=False)
    op.create_index(op.f('ix_user_chat_room_user_id'), 'user_chat_room', ['user_id'], unique=False)
    op.create_table('feedback_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False, comment='反馈图片url链接'),
    sa.Column('feedback_id', sa.Integer(), nullable=True, comment='反馈'),
    sa.Column('create_time', sa.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DATETIME(), nullable=True, comment='修改时间'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='状态'),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback_image')
    op.drop_index(op.f('ix_user_chat_room_user_id'), table_name='user_chat_room')
    op.drop_index(op.f('ix_user_chat_room_chat_room_id'), table_name='user_chat_room')
    op.drop_table('user_chat_room')
    op.drop_table('feedback')
    op.drop_table('chat_message')
    op.drop_table('feedback_reply')
    op.drop_table('chat_room')
    op.drop_table('user')
    op.drop_table('roles_permissions')
    op.drop_table('role')
    op.drop_table('permission')
    op.drop_table('feedback_type')
    # ### end Alembic commands ###
