"""'增加好友表发起人'

Revision ID: c9b1e864a749
Revises: cebc41251a56
Create Date: 2019-08-10 16:06:55.273827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9b1e864a749'
down_revision = 'cebc41251a56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_friend', sa.Column('initiator_id', sa.Integer(), nullable=True, comment='发起人'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_friend', 'initiator_id')
    # ### end Alembic commands ###
