"""'修改好友表'

Revision ID: cebc41251a56
Revises: fbe57a127bb0
Create Date: 2019-08-09 12:56:28.211822

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cebc41251a56'
down_revision = 'fbe57a127bb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_friend', sa.Column('status', sa.Enum('NOT_PASS', 'PASS', 'WAIT', 'LOSE', name='chatfriendstatus'), nullable=True, comment='审核状态'))
    op.drop_column('chat_friend', 'is_pass')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_friend', sa.Column('is_pass', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='审核通过'))
    op.drop_column('chat_friend', 'status')
    # ### end Alembic commands ###
