"""'新增消息表'

Revision ID: d5ba0761864c
Revises: 442a866dc869
Create Date: 2019-08-09 09:53:55.691286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5ba0761864c'
down_revision = '442a866dc869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('msg', sa.String(length=126), nullable=True, comment='聊天记录'),
    sa.Column('type', sa.SmallInteger(), nullable=True, comment='类型'),
    sa.Column('from_user_id', sa.Integer(), nullable=True, comment='发送者'),
    sa.Column('to_user_id', sa.Integer(), nullable=True, comment='接收者'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='接收状态'),
    sa.Column('room', sa.String(length=126), nullable=True, comment='房间名称'),
    sa.Column('create_time', sa.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DATETIME(), nullable=True, comment='修改时间'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='状态'),
    sa.ForeignKeyConstraint(['from_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends_message')
    # ### end Alembic commands ###
