"""'删除好友表中外键'

Revision ID: fbe57a127bb0
Revises: 758d175af84e
Create Date: 2019-08-09 10:50:40.586618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbe57a127bb0'
down_revision = '758d175af84e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chat_friend_friend_id'), 'chat_friend', ['friend_id'], unique=False)
    op.create_index(op.f('ix_chat_friend_self_id'), 'chat_friend', ['self_id'], unique=False)
    op.drop_constraint('chat_friend_ibfk_3', 'chat_friend', type_='foreignkey')
    op.drop_constraint('chat_friend_ibfk_2', 'chat_friend', type_='foreignkey')
    op.create_index(op.f('ix_friends_message_from_user_id'), 'friends_message', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_friends_message_to_user_id'), 'friends_message', ['to_user_id'], unique=False)
    op.drop_constraint('friends_message_ibfk_2', 'friends_message', type_='foreignkey')
    op.drop_constraint('friends_message_ibfk_1', 'friends_message', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('friends_message_ibfk_1', 'friends_message', 'user', ['from_user_id'], ['id'])
    op.create_foreign_key('friends_message_ibfk_2', 'friends_message', 'user', ['to_user_id'], ['id'])
    op.drop_index(op.f('ix_friends_message_to_user_id'), table_name='friends_message')
    op.drop_index(op.f('ix_friends_message_from_user_id'), table_name='friends_message')
    op.create_foreign_key('chat_friend_ibfk_2', 'chat_friend', 'user', ['friend_id'], ['id'])
    op.create_foreign_key('chat_friend_ibfk_3', 'chat_friend', 'user', ['self_id'], ['id'])
    op.drop_index(op.f('ix_chat_friend_self_id'), table_name='chat_friend')
    op.drop_index(op.f('ix_chat_friend_friend_id'), table_name='chat_friend')
    # ### end Alembic commands ###
