
export const RECEIVE_USERINFO='receive_userinfo'
export const RECEIVE_CONNECTSTATUS='receive_connectstatus'
export const RECEIVE_ROOMLIST='receive_roomlist'
export const RECIVE_NOWROOM='recive_nowroom'
export const RETSET_CONF='resetConf'
export const RECEIVE_HISTORY_MESSAGE='receive_history_message'
export const NEW_MESSAGE='new_message'
export const RECEIVE_FRIENDS='receive_friends'
export const RECEIVE_USER='receive_user'
export const RECEIVE_FRIEND_HISTORY='receive_friend_history'
export const RECEIVE_SOCKET_FRIEND_HISTORY_LIST='receive_socket_friend_history_list'
export const RECEIVE_SOCKET_FRIEND_HISTORY='receive_socket_friend_history'
export const RECEIVE_FRIEND_MSG_LIST='receive_friend_msg_list'
